#!/usr/bin/with-contenv bash
# Automatically configures the timezone if the TZ variable is set

if [ -n "$TZ" ]; then
    ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime
    echo "$TZ" > /etc/timezone
fi

